// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nooaqbvmnnswmhfahsmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vb2FxYnZtbm5zd21oZmFoc21iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NjU5NzcsImV4cCI6MjA2MDU0MTk3N30.R_VWjcCchzJ2rIW7BcrzUwQEtgKWb52cYInEWaJwOiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);